Add partial alternatives for subterm functions
FreeProving/free-compiler pull request #102
Opened 2020-06-29 10:11 UTC by Daniel-Teut

### Issue

Closes #52.

### Description of the Change

Adds partial versions of some subterm functions that throw an error instead of returning `Nothing`. Also replaces some function calls with the alternative version where appropriate.

### Alternate Designs

### Possible Drawbacks

### Verification Process

### Additional Notes

2020-06-29 18:33 UTC, just95 requested changes

2020-06-29 18:33 UTC, just95 commented on src/lib/FreeC/IR/Subterm.hs
> +class Pretty a => Subterm a where
The documentation for `Subterm` should explain why it is a subclass of `Pretty`.

2020-06-29 18:33 UTC, just95 commented on src/lib/FreeC/IR/Subterm.hs
> +replaceSubterms' = foldl (\term (pos, term') -> replaceSubterm' term pos term')
I like the solution using `foldl`. Could you rewrite `replaceSubterms` using `foldlM` as well? : )

2020-06-30 10:40 UTC, JonasHoefer approved these changes

2020-06-30 11:54 UTC, just95 approved these changes

2020-06-30 11:54 UTC, merged