Complete spell check of block 5
FreeProving/free-compiler pull request #105
Opened 2020-06-30 12:06 UTC by stu204146-kiel

### Issue

Is linked to Branch Spell check block 6

### Description of the Change

All files in block 5 were spell checked

2020-06-30 13:38 UTC, nbun approved these changes
It seems to me that both "schemas" and "schemata" are correct plural forms of "schema". As long as the usage is consistent, either one should be fine.

2020-07-01 16:21 UTC, just95 requested changes
I agree with @nbun that it is okay to write "schemata" instead of "schemas" as long as we do so consitently. However, since I wrote "schemas" everywhere else, this PR currently introduces inconsistencies. Thus, all other occurrence of "schemas" would have to be replaced as well. I took a look at the [original publication by Damas and Milner](https://web.cs.wpi.edu/~cs4536/c12/milner-damas_principal_types.pdf) to check which plural form they use. As it turns out, they do not call it a "schama" but a "scheme" (pl. "schemes"). Thus, I'd suggest to replace "schema" by "scheme" everywhere (including the names of the data type, constructor and variables).

2020-07-10 07:05 UTC, nbun commented
> Thus, I'd suggest to replace "schema" by "scheme" everywhere (including the names of the data type, constructor and variables).

@stu204146-kiel Have you considered this suggestion?

2020-07-10 08:30 UTC, just95 approved these changes

2020-07-15 14:02 UTC, merged