Implement a rudimentary sharing operator in Coq
FreeProving/free-compiler pull request #108
Opened 2020-07-03 09:18 UTC by MajaRet

### Issue

Closes #77

### Description of the Change

A non-functional, effect-generic sharing operator (as well as a strict version of it) was implemented in Coq. 
The operator simply takes a `Free` value and wraps it in an additional `Free` layer via `pure`. 
The strict version evaluates the argument first via `>>=` and then wraps it in two layers of `Free` with two applications of `pure`. 

### Alternate Designs

Right now, the operator operates on `Free` values with arbitrary effects. To get a functional `share` operator, the effect stack will be required to include effects for state and scoped sharing. 

### Possible Drawbacks

### Verification Process

### Additional Notes

2020-07-03 11:37 UTC, nbun requested changes
The sharing operators should have names that reflect their semantics, that is, they should include cbn and cbv.

2020-07-03 12:24 UTC, nbun approved these changes

2020-07-07 10:15 UTC, maclement approved these changes

2020-07-07 13:50 UTC, ichistmeinname approved these changes

2020-07-07 14:02 UTC, merged