Implement Comb, Share and Choice effects
FreeProving/free-compiler pull request #111
Opened 2020-07-03 13:27 UTC by MajaRet

### Issue

Closes #109 

### Description of the Change

The three effects `Comb` for the combination of effects, `Share` for sharing using explicit scope tags, and `Choice` for non-deterministic programs have been implemented in Coq.

### Alternate Designs

### Possible Drawbacks

### Verification Process

### Additional Notes

2020-07-06 07:06 UTC, nbun requested changes
Looks good to me, well done. For now I would prefer to keep the original `Id`, `Just` and `Nothing` constructors until we have the infrastructure for dynamically building the effect stack based on the input program.

2020-07-06 08:52 UTC, nbun approved these changes

2020-07-07 06:41 UTC, ichistmeinname commented on base/Free/Injectable.v
> +   }.
As these instances overlap (which we explicitly need to tackle in the Haskell code basis), I'd like to see some tests using `injS` and `injP` that show how to overcome the overlapping problem -- or to check if there is any problem at all.

Can you add the definition of tests to the corresponding ticket? We can discuss later, if we find another candidate, who might be interested in testing this (as part of the review process).

2020-07-07 08:38 UTC, MajaRet commented on base/Free/Injectable.v
> +   }.
These instances have explicitly assigned priorities (1 for `Inject_comb` and 2 for `Inject_rec`), so if I understand Coq's way of inferring instances correctly, Coq should always use `Inject_comb` when the instances overlap. I agree that we should add tests that test whether that's always the case. I'll add it to the ticket.

2020-07-07 11:08 UTC, maclement approved these changes
Looks good to me. Well done!

2020-07-07 14:40 UTC, merged