Use lifted IR for type translations
FreeProving/free-compiler pull request #112
Opened 2020-07-05 07:20 UTC by Daniel-Teut

### Issue
Closes #96.

### Description of the Change

Changes the translation of Haskell to Coq types so that the type translation of the lifted IR is used.

### Alternate Designs

### Possible Drawbacks

### Verification Process

The existing test suit is used to verify that the type translation is stil correct.
### Additional Notes

2020-07-05 12:03 UTC, just95 requested changes
Looks good to me. I just added some suggestions for the documentation.

2020-07-05 12:03 UTC, just95 commented on src/lib/FreeC/Backend/Coq/Converter/Type.hs
> +-------------------------------------------------------------------------------
```suggestion
-------------------------------------------------------------------------------
-- IR to Coq translation                                                     --
-------------------------------------------------------------------------------
```

2020-07-05 12:03 UTC, just95 commented on src/lib/FreeC/Backend/Coq/Converter/Type.hs
> +-------------------------------------------------------------------------------
```suggestion
-------------------------------------------------------------------------------
-- Lifted IR to Coq translation                                              --
-------------------------------------------------------------------------------
```

2020-07-05 12:03 UTC, just95 commented on src/lib/FreeC/Backend/Coq/Converter/Type.hs
> +-- | Converts a given type in the lifted IR to a coq term.
```suggestion
-- | Converts a given type in the lifted IR to a Coq term.
```

2020-07-05 12:03 UTC, just95 commented on src/lib/FreeC/Backend/Coq/Converter/Type.hs
>  -- | Converts a Haskell type to Coq, lifting it into the @Free@ monad.
We could use this opportunity to get the documentation up to date.

```suggestion
-- | Converts a type from IR to Coq, lifting it into the @Free@ monad.
```

2020-07-05 12:03 UTC, just95 commented on src/lib/FreeC/Backend/Coq/Converter/Type.hs
>  -- | Converts a Haskell type to Coq.
```suggestion
-- | Converts a type from IR to Coq.
```

2020-07-06 06:31 UTC, nbun approved these changes

2020-07-06 09:54 UTC, JonasHoefer approved these changes

2020-07-07 06:52 UTC, just95 approved these changes

2020-07-07 09:33 UTC, merged