Implement effect handlers #116
FreeProving/free-compiler pull request #118
Opened 2020-07-07 17:39 UTC by MajaRet

#10 
# Issue

### Description of the Change

Several effect handlers were defined:
- A handler for an effect-free program (`Identity` effect)
- A handler for programs containing `Maybe`
- A handler for non-deterministic programs (`ND` effect)
- A call-time-choice handler (`ND` and `Share` effect)

### Alternate Designs

Currently, the handlers assume that the effect stack is in a certain order: effects must be on the stack in the same order they are handled.
The first effect to be handled must be the topmost (leftmost) effect on the effect stack, and so on.
Additionally, the call-time choice handler assumes that the `Share` effect is directly followed by the `ND` effect on the stack.

We could drop these assumptions if we could define functions corresponding to `project` [(p.28)](https://bunkenburg.net/papers/ModelingCallTimeChoiceAsEffect.pdf) for our implementation. Unfortunately, I haven't figured out a way to do that yet that Coq accepts.

### Possible Drawbacks

As mentioned above, the handlers require that the effects be on the stack in the order they are handled. As a consequence, we will usually need to add an explicit type annotation to effectful values to make sure its effects are in the correct order when we want to use the handlers.

### Verification Process

### Additional Notes

We should attempt to define functions corresponding to `project` (or rather `prj`) so the handlers aren't dependent on the structure of the effect stack.

2020-07-09 11:53 UTC, ichistmeinname requested changes
Is there a concrete concern against defining the handlers together with their instances? In its current form, when I need the `run` handler, I get a lot of additional exported function that I won't need. As alternative to moving the handlers to their instance files, we can use modules to restrict the visibility of functions when import this file.

2020-07-09 11:53 UTC, ichistmeinname commented on base/Free/Handler.v
> +Definition ID : Type := nat * nat * nat.
This definition should stay closer to its usage (`runNDSharing`?)

2020-07-09 11:53 UTC, ichistmeinname commented on base/Free/Handler.v
> +  : Free Shape Pos (A * list (option ID * string)) :=
What's the `option ID` for?

2020-07-09 11:53 UTC, ichistmeinname commented on base/Free/Handler.v
> +  : Free (Comb.Shape ND.Shape Shape) (Comb.Pos ND.Pos Pos) A  :=
The identation of the types are a bit hard to read.

2020-07-09 11:53 UTC, ichistmeinname commented on base/Free/Handler.v
> +Fixpoint runNDSharing A {Shape : Type} {Pos : Shape -> Type}
Does the sharing handler need to be specific to the effect? It seems like there a lot of code parts that are duplicated.

2020-07-09 12:21 UTC, MajaRet commented on base/Free/Handler.v
> +  : Free (Comb.Shape ND.Shape Shape) (Comb.Pos ND.Pos Pos) A  :=
I'm working on that : )
I'll also define synonyms (such as `SNDShare` for `Comb.Shape Share.Shape (Comb.Shape ND.Shape Shape)` ) for the types so they're easier to read.

2020-07-09 12:24 UTC, MajaRet commented
Yes, I think it makes sense to put the handlers together with the instances.

2020-07-09 12:28 UTC, MajaRet commented on base/Free/Handler.v
> +  : Free Shape Pos (A * list (option ID * string)) :=
That's how we can determine which messages are different occurrences of the same shared variable. `option ID * string` is actually how `Trace.Shape` is defined. 
I haven't really tested this handler yet, so it may still change.

2020-07-09 12:32 UTC, MajaRet commented on base/Free/Handler.v
> +Definition ID : Type := nat * nat * nat.
It is used in `runTracing`, though.

2020-07-09 12:35 UTC, ichistmeinname commented on base/Free/Handler.v
> +  : Free Shape Pos (A * list (option ID * string)) :=
Ah, I see. That's the corresponding part to the ids used in the non-determinism effect.

2020-07-09 12:36 UTC, ichistmeinname commented on base/Free/Handler.v
> +Definition ID : Type := nat * nat * nat.
That, I got only later ; )

2020-07-09 13:12 UTC, MajaRet commented on base/Free/Handler.v
> +Fixpoint runNDSharing A {Shape : Type} {Pos : Shape -> Type}
The handler needs to take effect-specific actions (e.g. construct a `Choice` with the current scope and counter when it sees an `schoice`, and it needs to use `nameChoices` recursively to do that).
I think Niels is working on a more general solution, but that uses the higher-order approach to sharing, not our explicit scoping tag approach.

So unfortunately, I'm not sure we can avoid the duplication right now.

2020-07-09 13:51 UTC, ichistmeinname commented on base/Free/Handler.v
> +Fixpoint runNDSharing A {Shape : Type} {Pos : Shape -> Type}
Then let's just open a ticket for some other time!

2020-07-09 13:56 UTC, MajaRet commented on base/Free/Handler.v
> +Fixpoint runNDSharing A {Shape : Type} {Pos : Shape -> Type}
On it! : )

2020-07-10 08:41 UTC, nbun requested changes

2020-07-10 08:41 UTC, nbun commented on base/Free/Handler.v
> +    Maybe, as well as a handler for an effect-free program *)
```suggestion
(** Handlers for non-determinism, partiality, tracing and sharing of
    non-determinism and tracing, as well as a handler for
    effect-free programs *)
```

2020-07-10 08:41 UTC, nbun commented on base/Free/Util/Search.v
> +Definition beq_id (id1 id2 : ID) : bool :=
I know that this is probably my own code, but for the sake of consistency I would prefer camel case everywhere.

2020-07-10 08:41 UTC, nbun commented on base/Free/Handler.v
> +  | impure (inl ND.sfail) _ => pure (Empty A)
Writing `impure s pf` and then pattern matching on `s` instead of the whole pattern each time does lead to problems with the termination checker? I am not sure if I remember correctly and if this is still the case.

2020-07-20 06:32 UTC, ichistmeinname requested changes

2020-07-20 06:32 UTC, ichistmeinname commented on base/Free/Malias.v
> +      Put _ _ (i,j+1) >>
Maybe you should add notations for these smart constructors that infer there types?

2020-07-20 06:32 UTC, ichistmeinname commented on base/Free/Instance/Maybe.v
> +      (fun (x : Void) => match x with end) (injP p)).
A direct pattern match on `injP p` isn't possible, because Coq does not "know" its exact type, right?

2020-07-20 13:22 UTC, nbun approved these changes

2020-07-21 06:58 UTC, MajaRet commented on base/Free/Instance/Maybe.v
> +      (fun (x : Void) => match x with end) (injP p)).
That's right. Writing 
```Coq
(...) := impure (injS tt) (fun p : Pos' (injS tt) => 
      match injP p with end).
```
causes the error message
```
Found a matching with no clauses on a term unknown to have an empty inductive type.
```

2020-07-21 07:11 UTC, MajaRet commented on base/Free/Malias.v
> +      Put _ _ (i,j+1) >>
Now that I think about it, it could be dangerous to infer the types at all. For example, 
```Coq
Definition p := cbneed (pure true) >>= sx => sx.
``` 
is a valid program right now, but its type is now fixed as `Free Share.Shape Share.Pos (Bool Shape Pos)`, so we cannot add any other effects (e.g. define something that contains `Choice p p`) or properly handle the program.

`cbneed` shouldn't really be used by the user (especially if we abstract sharing through a typeclass (#137) ), but it still seems like a better idea to make `Shape` and `Pos` explicit.

2020-07-21 08:27 UTC, nbun approved these changes

2020-07-21 14:52 UTC, ichistmeinname commented on base/Free/Malias.v
> +      Put _ _ (i,j+1) >>
I'm not sure why a more polymorphic type wouldn't work here? Something like `Share :<: sig` in Haskell-notation.

2020-07-22 06:10 UTC, ichistmeinname approved these changes

2020-07-22 11:44 UTC, merged