Implement a tracing effect in Coq
FreeProving/free-compiler pull request #122
Opened 2020-07-08 16:42 UTC by MajaRet

### Issue

Closes #120

### Description of the Change

A tracing effect (as well as a `trace` operator) was implemented in Coq.

### Alternate Designs

### Possible Drawbacks

### Verification Process

### Additional Notes

2020-07-09 13:51 UTC, ichistmeinname requested changes

2020-07-09 13:51 UTC, ichistmeinname commented on base/Free/Instance/Trace.v
> +  Definition ID : Type := nat * nat * nat.
Maybe we should add a dedicated module for all constructs and helper functions related to sharing. If I'm not mistaken, you use the same definition for `ND`.

2020-07-09 13:55 UTC, MajaRet commented on base/Free/Instance/Trace.v
> +  Definition ID : Type := nat * nat * nat.
Good idea.

2020-07-09 18:20 UTC, marvin2706 commented on base/Free/Instance/Trace.v
> +  Definition ID : Type := nat * nat * nat.
I would also prefer to have the share-related definitions like `ID` in a single location instead of defining them in each file where we need it.

2020-07-11 11:23 UTC, ichistmeinname approved these changes

2020-07-11 15:25 UTC, MarvinLira approved these changes

2020-07-11 15:30 UTC, merged