Add Agda Backend
FreeProving/free-compiler pull request #130
Opened 2020-07-14 19:36 UTC by Daniel-Teut

### Issue
#98, #99

### Description of the Change

Add the Agda Backend instance.

### Alternate Designs

### Possible Drawbacks

### Verification Process

### Additional Notes

2020-07-17 11:11 UTC, JonasHoefer requested changes

2020-07-17 11:11 UTC, JonasHoefer commented on src/exe/FreeC/Backend.hs
> +  return $ showPretty $ PrettyAgda ast'
This implementation can be minimized. The `PrettyAgda` isn't needed. 
```suggestion
convertModuleToAgda =
  fmap showPretty . liftConverter . Agda.Converter.convertModule
```
With this implementation the import can be simplified to `import FreeC.Backend.Agda.Pretty ()`.

2020-07-17 11:11 UTC, JonasHoefer commented on src/lib/FreeC/Backend/Agda/Converter/Module.hs
> +    <$> getAp (importDecls' <> typeDecls' <> funcDecls')
Maybe we can use this PR to fix the `modul` typo.
```suggestion
convertModule irModule@(IR.Module _ name importDecls typeDecls _ _ funcDecls) = do
  mapM_ (addDecArgPragma (IR.modFuncDecls irModule)) (IR.modPragmas irModule)
  Agda.moduleDecl (convertModName name)
    <$> getAp (importDecls' <> typeDecls' <> funcDecls')
```

2020-07-18 10:55 UTC, JonasHoefer approved these changes

2020-07-19 12:05 UTC, just95 approved these changes

2020-07-19 19:31 UTC, merged