Dev agda
FreeProving/free-compiler pull request #140
Opened 2020-07-20 07:34 UTC by JonasHoefer

### Issue

[Agda Backend](https://github.com/FreeProving/free-compiler/projects/1)

### Description of the Change

- second back end for Agda
- moves lifting from the coq back end to the new lifted IR 

### Possible Drawbacks

Every user of the free compiler has to build the Agda dependency.

### Verification Process

We tested the new back end with a new set of tests and some case studies.

2020-07-20 07:55 UTC, nbun approved these changes

2020-07-20 09:49 UTC, just95 requested changes
In this review I've tried to focus on the user's perspective. I've added some comments for how to improve the documentation and error messages. Additionally, we should mention the addition of an Agda backend in the `CHANGELOG.md`.

2020-07-20 09:49 UTC, just95 commented on src/lib/FreeC/Backend/Agda/Converter/FuncDecl.hs
> +  error "Mutual recursive functions are not supported at the moment."
Let's use `reportFatal` here.

2020-07-20 09:49 UTC, just95 commented on src/lib/FreeC/Backend/Agda/Converter/TypeDecl.hs
> +  error "Type synonyms are not supported at the moment."
Use `reportFatal` here, too.

2020-07-20 09:49 UTC, just95 commented on src/lib/FreeC/LiftedIR/Converter/Type.hs
> +  error "liftTypeApp': Only type constructors can be applied!"
Due to the `KindCheckPass`, this error should not occur in practice. However, we should probably still use `reportFatal` here (which would require `liftType` to be lifted into the `Converter` monad, though).

2020-07-20 09:49 UTC, just95 commented on src/lib/FreeC/LiftedIR/Converter/Type.hs
> +  error "Outermost argument is not necessarily unique"
This error can defiantly be triggered by using a decreasing argument pragmas. Thus `reportFatal` should be used here as well.

2020-07-20 09:49 UTC, just95 commented on README.md
>     The Coq base library is a collection of Coq files that are required by the generated code.
We should add a bullet point for the `./base/agda` library.

2020-07-20 09:49 UTC, just95 commented on README.md
>  > ```
Is there anything the user needs to know about the Agda base library and how to install and use it?

2020-07-20 09:49 UTC, just95 commented on free-compiler.cabal
> +                   , base/coq/Test/*.vo
We should maybe copy the Agda base library to the compiler's installation directory as well.

2020-07-20 09:49 UTC, just95 commented on .github/workflows/ci-pipeline.yml
> +          -b ./base/coq                                  \
It's a bit weird that the user has to point to the Coq base library even if they want to compile to Agda. The `*.toml` files should be moved to `./base` or there should be another set of `*.toml` files in `./base/agda`.

2020-07-24 13:35 UTC, just95 approved these changes

2020-07-24 16:04 UTC, merged