Translate Coq Expressions using the lifted IR
FreeProving/free-compiler pull request #141
Opened 2020-07-21 00:57 UTC by Daniel-Teut

### Issue
Closes #123.

### Description of the Change
Change the translation of Coq expressions such that the lifted IR translation for expressions is used.

### Alternate Designs

### Possible Drawbacks

### Verification Process

### Additional Notes

2020-07-28 20:01 UTC, just95 requested changes

2020-07-28 20:01 UTC, just95 commented on src/lib/FreeC/Backend/Coq/Converter/Expr.hs
> +        [ Coq.Qualid (fst Coq.Base.partialArg) | Partiality `elem` effects ]
I'd suggest to add a function `convertEffect` that performs pattern matching on `Effect` such that GHC produces a warning if a new effect is added that is not handled by the back end.

2020-07-28 20:01 UTC, just95 commented on src/lib/FreeC/Backend/Coq/Converter/Free.hs
> +  -> Coq.Term
```suggestion
  :: Coq.Term   -- ^ The function or (type) constructor term
  -> [Coq.Term] -- ^ The type class instances to pass to the callee.
  -> [Coq.Term] -- ^ Implicit arguments to pass explicitly to the callee.
  -> [Coq.Term] -- ^ The actual arguments of the callee.
  -> Coq.Term
```

2020-07-28 20:01 UTC, just95 commented on src/lib/FreeC/LiftedIR/Syntax/Expr.hs
> +        , exprFreeArgs    :: Bool     -- ^ If the arguments for the free monad are needed.
```suggestion
        , exprFreeArgs    :: Bool     -- ^ Whether the arguments for the free
                                      --   monad are needed.
```

2020-07-28 20:01 UTC, just95 commented on src/lib/FreeC/LiftedIR/Syntax/Expr.hs
> +                  , stringValue :: String
Since the `intLiteralValue` field has `Literal` in the name, I'd do the same for string literals.

```suggestion
                  , stringLiteralValue :: String
```

2020-07-28 20:01 UTC, just95 commented on src/lib/FreeC/LiftedIR/Converter/Expr.hs
>    argIdent <- freshIRQName $ fromMaybe "f" (guessName arg)
I must have missed this in a previous review but the prefixes of fresh variables should are [defined in `FreeC.Environment.Fresh`](https://github.com/FreeProving/free-compiler/blob/8779013877645b9547bb36c93fa1df9856b2b1aa/src/lib/FreeC/Environment/Fresh.hs#L46) and shouldn't be hard coded. The prefix `f` for example should only be used in applications whereas `cond` should be used by default in `if` expressions. Can you add an additional argument to `bind` and for the right `fresh*Prefix`?

2020-07-29 07:34 UTC, just95 approved these changes

2020-07-30 07:03 UTC, nbun approved these changes
Good job!

2020-07-30 14:13 UTC, merged