Implement Normalform typeclass
FreeProving/free-compiler pull request #170
Opened 2020-08-24 15:58 UTC by MajaRet

### Issue

Closes #148 

### Description of the Change

This PR implements a typeclass `Normalform` that allows us to move effects from the components of a data structure to its root. 
For example, the list [0 ? 1, 2] with a non-deterministic element is transformed into the non-deterministic list [0, 2] ? [1, 2]. 
This allows us to handle such programs with effects in the components of data structures.

The class `Normalform` is parameterized over `Shape`, `Pos`, and two types `A` and `B` which features the following components:

- `nf`, which, applied to a `Free Shape Pos A`, returns a `Free Shape Pos B`.
- `nf'`, which, applied to an `A`, returns a `Free Shape Pos B`. 
- `nf_impure`, which is a property that defines how `nf` is moved into the position function of an impure value.
- `nf_pure`, which is a property that defines how `nf` is unfolded on pure values.

The type parameter `B` describes the change of the original type `A` to an effect-free version of the same type.
Thus, for a type `T Shape Pos`, we define the `Normalform` instance `Normalform Shape Pos (T Shape Pos) (T Identity.Shape Identity.Pos)`.

### Verification Process

A testing module `NormalizationTests` is included that tests normalization of lists of boolean values. It considers the effects non-determinism, partiality and tracing.
In addition, programs in `SharingHandlerTests` are now normalized before they are evaluated. The tests continue to pass.

2020-08-26 11:04 UTC, marvin2706 requested changes

2020-08-26 11:04 UTC, MarvinLira commented on base/coq/Prelude/Bool.v
> +    := n >>= (fun n' => pure n').
This can be written easier. This also applies to `Integer` and `Unit`.
```suggestion
    := n >>= pure.
```

2020-08-26 11:04 UTC, MarvinLira commented on base/coq/Prelude/Bool.v
> +Variable Pos : Shape -> Type.
There should be 2 spaces of indentation inside of sections. You should check this also in the other files.
```suggestion
  Variable Shape : Type.
  Variable Pos : Shape -> Type.
```

2020-08-26 11:04 UTC, MarvinLira commented on base/coq/Prelude/List.v
> + := p >>= (fun p' => nf'List p').
This can be written easier. This also applies similarly to `Pair`.
```suggestion
 := p >>= nf'List.
```

2020-08-26 11:04 UTC, MarvinLira commented on base/coq/Free/Class/Normalform.v
> +  }.
The definition of `nf` seems to be always the same.
Couldn't you define this like the following?
That way, you would also not have to do the proofs in every instance definition.
```suggestion
Class Normalform {Shape : Type} {Pos : Shape -> Type}
                 (A B : Type) :=
  {
    (** The function is split into two parts due to termination check errors
        for recursive data types. *)
    nf' : A -> Free Shape Pos B
  }.

Definition nf {Shape : Type} {Pos : Shape -> Type}
    (A B : Type)
    {n : Normalform A B}
    (fx : Free Shape Pos A)
   : Free Shape Pos B :=
  fx >>= nf'.

(** Property for moving nf into position functions *)
Lemma nf_impure : forall {Shape : Type} {Pos : Shape -> Type}
    (A B : Type)
    (n : Normalform A B)
    s (pf : _ -> Free Shape Pos A),
    nf A B (impure s pf) = impure s (fun p => nf A B (pf p)).
Proof.
  trivial.
Qed.

(** Property for unfolding nf on pure values *)
Lemma nf_pure : forall {Shape : Type} {Pos : Shape -> Type}
    (A B : Type)
    (n : Normalform A B)
    (x : A),
  @nf Shape Pos A B n (pure x) = nf' x.
Proof.
  trivial.
Qed.

```

2020-08-26 11:04 UTC, MarvinLira commented on base/coq/Free/Verification/SharingHandlerTests.v
> +in f sx (f (sy (f sz val)))
```suggestion
in f sx (f sy (f sz val)) 
```

2020-08-26 11:29 UTC, MajaRet commented on base/coq/Free/Class/Normalform.v
> +  }.
That is a very good point and it will make things a lot simpler. Thank you!

2020-08-26 12:14 UTC, marvin2706 approved these changes

2020-08-31 07:33 UTC, nbun approved these changes

2020-08-31 07:33 UTC, nbun commented on base/coq/Free/Verification/NormalizationTests.v
> +   list without normalization. *)
```suggestion
(* Shortcut to evaluate a non-deterministic program to a result list
   without normalization. *)
```

2020-08-31 08:56 UTC, merged