Adapt sharing infrastructure to flexible strategy approach
FreeProving/free-compiler pull request #184
Opened 2020-09-01 14:54 UTC by MajaRet

### Issue

#183 

### Dependencies

Depends on changes currently up for review in #173.

### Description of the Change

The `Shareable` class has been renamed to `Strategy`.
Another function `call : forall {A : Type}, Free Shape Pos A -> Free Shape Pos (Free Shape Pos A)` has also been added to `Strategy` to translate `let` bindings whose value does not occur more than once.

In addition, a `Cbv` instance of `Strategy` for call-by-value evaluation has been added.

### Alternate Designs

This design lets us avoid choosing an evaluation strategy at compile time. Alternate designs could, for example, let the user choose an evaluation strategy via a compiler flag. However, this could lead to inconsistencies if programs compiled with different evaluation options are combined. 

The additional function `call` is used to avoid unnecessary applications of `share` in a call-by-need setting, which would complicate the program and thus any proofs about it.
Alternatively, we could remove `call` and instead always use `share` to translate `let` bindings.  

### Verification Process

The changes were not specially verified. We could potentially add tests for the call-by-value evaluation, though.

2020-09-02 11:23 UTC, just95 commented on base/coq/Free/Class/Strategy.v
> +  }.
Some files are missing a [trailing newline](https://github.com/FreeProving/guidelines/blob/main/CONTRIBUTING.md#include-newline-at-end-of-file). There are also [trailing spaces](https://github.com/FreeProving/guidelines/blob/main/CONTRIBUTING.md#avoid-trailing-whitespace) that should be removed.
Most editors can be configured to make these changes automatically when a file is saved but I think the CoqIDE does not have such an option. Consider to open and save modified Coq files in another editor before committing your changes.

2020-09-02 11:23 UTC, just95 commented on base/coq/Free/Verification/SharingHandlerTests.v
> +(* Shortcut to evaluate a traced partial pro gram to a result and a list
```suggestion
(* Shortcut to evaluate a traced partial program to a result and a list 
```

2020-09-02 11:23 UTC, just95 commented on base/coq/Prelude/Pair.v
> +
If we make these functions part of the `Prelude`, we should also expose them to the user by adding them to the `Prelude.toml` file.

2020-09-04 12:04 UTC, MajaRet commented on base/coq/Prelude/Pair.v
> +
For now, I've removed them from the `Prelude` again and put them in a utility module that the tests use.

2020-09-08 13:41 UTC, just95 requested changes

2020-09-08 13:41 UTC, just95 commented on base/coq/Free/Instance/ND.v
> +    Definition Choice_(Shape' : Type) (Pos' : Shape' -> Type)
```suggestion
    Definition Choice_ (Shape' : Type) (Pos' : Shape' -> Type)
```

2020-09-08 13:41 UTC, just95 commented on base/coq/Free/Class/Traceable.v
> -  }.
The problem with removing the `Traceable` type class is that we force the user to use our implementation of the `Trace` effect. They cannot provide their own implementation. Furthermore, the `Injectable` constraint adds a strong coupling between compiler and base library. Thus, I think that we shouldn't remove the type class even if we have only one implementation right now.

2020-09-09 10:43 UTC, MajaRet commented on base/coq/Free/Class/Traceable.v
> -  }.
That makes sense, but I'm a little worried about proofs. 
Any traced value would essentially become a black box when we use an unknown `Traceable` instance, which might make a proof about a program with tracing very difficult.
Using a specific `Traceable` instance in a theorem about a translated QuickCheck property means that the `Shape` and `Pos` arguments (plus any constraints on `Shape` and `Pos`) of a property need to be quantified in the theorem itself because we need to specify `Shape` and `Pos` for a `Traceable` instance. 
But if that's acceptable, I agree that it does make sense to keep the class in the interest of flexibility.

Even without tracing, we do also have another `Injectable` constraint for the `Share` effect. We _could_ potentially get rid of that, as well, but that could make type signatures large and somewhat cryptic, and would likely make translation more complicated. (See conversation on [this PR](https://github.com/FreeProving/free-compiler/pull/173).)

2020-09-10 09:41 UTC, nbun approved these changes

2020-09-10 20:46 UTC, just95 approved these changes

2020-09-10 20:50 UTC, merged