Implement default handling functions
FreeProving/free-compiler pull request #189
Opened 2020-09-04 21:04 UTC by MajaRet

### Issue

Closes #177 

### Description of the Change

A set of handling functions has been defined. A handling function evaluates all effects of a particular effect stack and produces a pure value of a certain type.

For given `Shape` and `Pos`, a handling function has the following type:
```coq
handle : Free Shape Pos A -> B
```

`B` is the type `A` is transformed into when the effects defined by `Shape` and `Pos` are handled.
For example, handling non-determinism turns a program of type `A` into a value of type `list A`. 
Handling tracing turns a program of type `A` into a value of type `A * list string`, where `A` ist the type of the result and `list string` is the message log.

A function of this type will be included as a parameter of a translated property so we can reason about the _semantics_ of a program (statements about its results when evaluated).

Handling functions are built for fixed effect stacks by combining individual effect handlers (e.g. `runChoice` or `runMaybe`). Therefore, there is one default handling function for almost any combination of effects, but the order of the effects in the stack is fixed. 
To use an alternative order, one can simply combine effect handlers themselves.

There are no default handling functions for effect stacks that contain all three effects sharing, tracing and non-determinism, as only one effect can currently be shared. 

A sharing handler for effects that do not interact with sharing has also been implemented. Without it, the sharing effect would have had to be handled with either the tracing or non-determinism handler, which unnecessarily introduces those effects into the effect stack and is reflected in the handling result (for example, the result is wrapped in a list if the non-determinism sharing handler is used). 

### Alternate Designs

As an alternative to a handling function, we could also implement a `Handler` typeclass (and that is what was done at first). However, as inferring `Handler` instances turned out to have unwanted results and the possibility to infer instances was the main advantage of a class, the function approach has been chosen. This way, a handling function must always be given explicitly when reasoning about a concrete effect stack and can no longer be inferred.  

### Possible Drawbacks

Because one default handling function usually contains more than one effect, they cannot be defined in the individual effects' modules like the simple effect handler functions (`runChoice`, `runMaybe` etc.).
Therefore, they are defined centrally in a module `Handlers`, which will make _all_ default handling functions available when imported.

Since there is a default handler for almost any combination of effects (disregarding order), the number of functions roughly doubles with every new effect.
But as long as effects are not added too often, this should still be manageable.

### Verification Process

Handling in the test modules is now done by calling the appropriate default handling function on a program (except for cases of non-standard handling without normalization in `NormalizationTests`). 
The tests still succeed.

2020-09-11 07:35 UTC, nbun requested changes

2020-09-11 07:35 UTC, nbun commented on base/coq/Free/Handlers.v
> +(** Definitions for the (p : Free class. *)
```suggestion
(** Handler definitions for the Free class. *)
```

2020-09-11 07:35 UTC, nbun commented on base/coq/Free/Handlers.v
> +(* No effect *)
Sections would be useful here, IMO.

2020-09-11 07:35 UTC, nbun commented on base/coq/Free/Handlers.v
> +(* Share :+: Identity handler *)
I guess this definition is technically valid, but is there a reason why one would have only sharing without a shared effect in the effect stack?

2020-09-11 07:35 UTC, nbun commented on base/coq/Free/Handlers.v
> +(* Maybe :+: Share :+: Identity handler *)
Why is `Share` not on top of the effect stack as for `handleShareND` and `handleShareTrace`?

2020-09-11 07:45 UTC, MajaRet commented on base/coq/Free/Handlers.v
> +(* Share :+: Identity handler *)
Every translated function that contains either the `call` or the `share` function (which is basically every function for a flattened program) has a constraint for the `Share` effect, so the `Share` effect will _always_ be in the effect stack, whether there are any other effects or not. 
So we still need a handler that removes the sharing syntax.

2020-09-11 07:55 UTC, MajaRet commented on base/coq/Free/Handlers.v
> +(* Maybe :+: Share :+: Identity handler *)
`Share` is not always the topmost effect. `Maybe` needs to be on top if `Trace` is in the effect stack along with sharing, it needs to be at the bottom (just above `Identity`) if `ND` is in the effect stack along with sharing, but in this case I don't think it matters what the order is. 
I could change it, though.

2020-09-11 07:59 UTC, MajaRet commented on base/coq/Free/Handlers.v
> +(** Definitions for the (p : Free class. *)
Oh, that was search-and-replace gone wrong. It should actually say something like "This module contains default handlers for individual effect stacks." or something.

2020-09-11 08:00 UTC, nbun commented on base/coq/Free/Handlers.v
> +(* Share :+: Identity handler *)
I see, good point.

2020-09-11 08:03 UTC, nbun commented on base/coq/Free/Handlers.v
> +(* Maybe :+: Share :+: Identity handler *)
For consistency's sake I would prefer a version with `Share` on top.

2020-09-14 07:30 UTC, nbun approved these changes

2020-09-14 15:34 UTC, marvin2706 approved these changes

2020-09-14 15:40 UTC, merged