[WIP] Start Agda base library
FreeProving/free-compiler pull request #34
Opened 2020-05-26 10:32 UTC by JonasHoefer

Imports the `Free` monad and some utilities from the [free proving Agda code](https://github.com/FreeProving/free-proving-agda-code) project. Checks Agda base lib during CI Pipeline runs.

2020-05-26 17:51 UTC, just95 requested changes

2020-05-26 17:51 UTC, just95 commented on base/agda/Free/Maybe.agda
> +Shape = ⊤
```suggestion
Shape : Set
Shape = ⊤
```

2020-05-26 17:51 UTC, just95 commented on base/agda/Free/Maybe/Properties.agda
> +to∘from Maybe≃MaybeF (impure tt x) = cong (impure tt) (∀-extensionality λ())
Since the Coq base library does not contain the isomorphism, I'd not include them in the Agda base library either. They are not needed for the translation and are usually also not needed for proofs about translated programs.

2020-05-26 17:51 UTC, just95 commented on tool/check-agda.sh
> +done
The `while …; do` notation that you are using above is what I'm familiar with (and use in the other scripts). For the sake of consistency I'd update the `for` loop (including the loop in the CI pipeline) to use the same notation.

```suggestion
for f in $(find . -name "*.agda"); do
  agda "$f"
done
```

2020-05-26 17:51 UTC, just95 commented on tool/check-agda.sh
> +# change into the directory containing the Agda modules
Please make ure that all comments (including comments in `.agda` files) are full sentences.

```suggestion
# Change into the directory containing the Agda modules.
```

2020-05-26 17:51 UTC, just95 commented on base/agda/Free/Maybe.agda
> +module Free.Maybe where
In the Coq base library the instances of the `Free` monad have the common prefix `Free.Instance`. I'd recommend to keep the same general structure of the Coq base library in the Agda base library.

```suggestion
module Free.Instance.Maybe where
```

2020-05-26 17:51 UTC, just95 commented on base/agda/Free/Maybe.agda
> +Just x = pure x
Please make sure that all source files end with a newline character (if permitted by the file format).

2020-05-26 17:51 UTC, just95 commented on base/agda/Free.agda
> +liftA2 f x y = pure f ⊛ x ⊛ y
I don't think we need `_⊛_` and `liftA2` for the translation to Agda. Thus, I wouldn't include them in the base library.

2020-05-26 17:51 UTC, just95 commented on tool/full-test.sh
> +     "./tool/check-agda.sh -r base/agda"
Since `./tool/check-agda.sh` uses `agda`, `agda` must be added to `check_required_software`.

2020-05-26 17:51 UTC, just95 commented on tool/check-agda.sh
> +while getopts "r" opt; do
The problem with `getopts` is that it does not support long option names (such as `--recompile`). Short options such as `-r` are easy to type but can be confusing to new users. That's why I "parse" the command line options manually in the other scripts. Alternatively, we could try [`getopt`](https://www.man7.org/linux/man-pages/man1/getopt.1.html) which seems to support long options.

2020-05-26 19:01 UTC, ichistmeinname commented on base/agda/Free/Maybe/Properties.agda
> +to∘from Maybe≃MaybeF (impure tt x) = cong (impure tt) (∀-extensionality λ())
Maybe we can add a `Meta`-directory, where we can include such "meta formalisms". Could be a nice finger-exercise to add these proofs for Coq as well.

2020-05-27 11:37 UTC, just95 requested changes

2020-05-27 11:37 UTC, just95 commented on base/agda/Free/Instance/Maybe/Properties.agda
> +
```suggestion
```

2020-05-27 11:37 UTC, just95 commented on base/agda/Free/Instance/Identity.agda
> +Identity = Free Shape Position
Most `.agda` files still don't have a trailing newline.

2020-05-27 11:37 UTC, just95 commented on base/agda/Free.agda
> +-- free monad over shapes S and positions P
The comments in the `.agda` files should also be proper sentences and formatted using Markdown.

2020-05-27 12:18 UTC, ichistmeinname approved these changes

2020-05-27 12:42 UTC, just95 approved these changes

2020-05-27 12:43 UTC, merged