Implement error effect in Coq #18
FreeProving/free-compiler pull request #40
Opened 2020-05-29 14:23 UTC by marvin2706

- Add implementation as described in [here](https://github.com/FreeProving/free-proving-code/blob/master/src/Effects.v).
- Add an example function in haskell that throws an error and a simple QuickCheck property for that function.
- Add proofs concerning error messages in addition to the proof of the QuickCheck property in the corresponding Coq file.

2020-05-29 18:43 UTC, just95 requested changes

2020-05-29 18:43 UTC, just95 commented on base/Free/Instance/Error.v
> +
Since `Free` exports `Coq.Strings.String`, this import is not necessary. We should probably also remove the import from `Maybe.v`.

2020-05-29 18:43 UTC, just95 commented on base/Free/Instance/Error.v
> +  Close Scope string_scope.
Is there a reason why you use `Open Scope string_scope.` instead of `"undefined"%string`?

2020-05-29 18:43 UTC, just95 commented on example/Proofs/ConsUncons.hs
> +-- First we have to define the @uncons@ function in an error throwing way.
In the comments and in the error message you wrote `uncons` instead of `unconsE`.

2020-05-29 18:43 UTC, just95 commented on example/Proofs/ConsUnconsProofs.v
> +Qed.
This is a good introductory example. However, you don't actually use the `Error` monad here. This proof holds for any monad with a `Partial` instance.  Thus, I think that you should add another proof to highlight the differences between `Maybe` and `Error`. 
For example, a property that involves several different error messages could be interesting. You could show for example that `fst (unconsE xs) === head xs` holds in the `Maybe` monad but not in the `Error` monad (since the error messages differ).

2020-05-29 18:43 UTC, just95 commented on example/Proofs/ConsUnconsProofs.v
> +End ErrorMessages.
Please end source files with a newline.

2020-05-30 13:43 UTC, ichistmeinname requested changes

2020-05-30 13:43 UTC, ichistmeinname commented on example/Proofs/ConsUnconsProofs.v
> +  Close Scope string_scope.
I'd suggest to use `"string"%string`-syntax for all error messages instead of opening and closing scopes.

2020-05-30 13:43 UTC, ichistmeinname commented on example/Proofs/ConsUnconsProofs.v
> +  @unconsE _ _ _ A (Nil _ _) = EmptyListError.
Here's an indentation missing.

2020-05-30 13:43 UTC, ichistmeinname commented on base/Free/Instance/Error.v
> +    Definition Error (E A : Type) := Free (Shape E) Pos A.
Not sure about this, but can this mix of implicit and explicit type arguments cause problems for generated code? 
Not specific to your PR, but more of a general question: how do I know which arguments to make explicit and which not; are these intricacies already documented?

2020-05-30 15:26 UTC, marvin2706 commented on base/Free/Instance/Error.v
> +    Definition Error (E A : Type) := Free (Shape E) Pos A.
This file compiles correctly and doesn't cause errors when using it in my example. If you're referring to the code generated by freec, this should also cause no problems as freec only uses the `Partial` class and uses `@` to make all arguments explicit.
When deciding which arguments to make explicit, I make those arguments explicit that I would also need in haskell code and the remaining arguments implicit.

2020-05-31 08:02 UTC, ichistmeinname commented on base/Free/Instance/Error.v
> +    Definition Error (E A : Type) := Free (Shape E) Pos A.
Ah, right, thanks for clarification!

2020-05-31 08:04 UTC, ichistmeinname approved these changes
Good job!

2020-05-31 09:20 UTC, just95 requested changes

2020-05-31 09:20 UTC, just95 commented on example/Proofs/ConsUnconsProofs.v
> +(* The second QuickCheck property holds provable for the [Maybe] instance of [Partial]. *)
I think `provable` should be an adverb here.

```suggestion
(* The second QuickCheck property holds provably for the [Maybe] instance of [Partial]. *)
```

2020-05-31 09:20 UTC, just95 commented on example/Proofs/ConsUnconsProofs.v
> +  Definition EmptyListError {A : Type} := @error _ _ _ A "unconsE: empty list"%string.
The reason `freec` uses explicit arguments for `Partial` instances is that implicit type class arguments behave counter-intuitively in Coq. In this case the `Error` instance is selected since it's the last instance imported at the top of the file.

```coq
From Base Require Import Free Free.Instance.Maybe Free.Instance.Error Test.QuickCheck Prelude.

…

Check EmptyListError.
(* ==> EmptyListError 
           : Free (Error.Shape string) Error.Pos ?A
       where
       ?A : [ |- Type]
*)
```

Suppose that we decide to sort imports in Coq alphabetically in the future as we do in Haskell already.

```coq
From Base Require Import Free Free.Instance.Error Free.Instance.Maybe Prelude Test.QuickCheck.
```

Now the import of the `Maybe` instance occurs last. Thus, the `Maybe` instance is inferred by Coq.

```coq
Check EmptyListError.
(* ==> EmptyListError
            : Free Maybe.Shape Maybe.Pos ?A
       where
       ?A : [ |- Type]
*)
```

However, all proofs below still hold in the `Maybe` monad  (including `unconsE_only_empty_list_error` which uses `NoError`) and the error goes unnoticed. Thus, I think that the `Partial` instance should be specified explicitly everywhere.

2020-05-31 09:20 UTC, just95 commented on example/Proofs/ConsUncons.hs
> +-- And we define a property thats validity depends on the model used in the proof.
```suggestion
-- And we define a property whose validity depends on the model used in the proof.
```

2020-05-31 11:43 UTC, just95 approved these changes

2020-06-11 12:26 UTC, maclement approved these changes
I have nothing to add or criticize. Well done!

2020-06-11 12:55 UTC, merged