Add Partial to reserved identifiers #16
FreeProving/free-compiler pull request #43
Opened 2020-06-01 19:38 UTC by stu204146-kiel

2020-06-04 22:34 UTC, Daniel-Teut requested changes

2020-06-04 22:34 UTC, Daniel-Teut commented on src/lib/FreeC/Backend/Coq/Base.hs
> +-- | The name of the type class @Partial@
```suggestion
-- | The Coq identifier for the @Partial@ type class.
```
I would change the wording here slightly to be more in line with the rest of the comments.

2020-06-05 14:25 UTC, Daniel-Teut approved these changes

2020-06-09 18:37 UTC, just95 approved these changes

2020-06-10 10:18 UTC, merged