Test cases for #21
FreeProving/free-compiler pull request #68
Opened 2020-06-17 08:50 UTC by MajaRet

Adds unit tests for the `CompletePatternPass`.

2020-06-18 10:10 UTC, maclement requested changes
I only added two very minor suggestions. Besides that i am really happy with the test cases.

Maybe we should add one or two test cases that check if type synonyms are handled correctly.
Some were mentioned in #42.

2020-06-18 10:10 UTC, maclement commented on src/test/FreeC/Pass/CompletePatternPassTests.hs
> +    it "fails if the case expression's scrutinee is a lambda" $ do
```suggestion
    it "fails if the case expression's scrutinee is a lambda expression" $ do
```

2020-06-18 10:10 UTC, maclement commented on src/test/FreeC/Pass/CompletePatternPassTests.hs
> +
```suggestion

```

2020-06-18 10:46 UTC, just95 requested changes

2020-06-18 10:46 UTC, just95 commented on src/test/FreeC/Pass/CompletePatternPassTests.hs
> +testCompletePatternPass = describe "FreeC.Pass.CompletePatternPass" $ do
You don't really need the heading if there is just a single function in your module. However, there should be documentation for the function itself.

```suggestion

-- | Test group for "FreeC.Pass.CompletePatternPass" tests.
testCompletePatternPass :: SpecWith ()
testCompletePatternPass = describe "FreeC.Pass.CompletePatternPass" $ do
```

2020-06-18 10:46 UTC, just95 commented on src/test/FreeC/Pass/CompletePatternPassTests.hs
> +-- | This module contains tests for "FreeC.Pass.CompletePatternPassTests".
```suggestion
-- | This module contains tests for "FreeC.Pass.CompletePatternPass".
```

2020-06-18 10:46 UTC, just95 commented on src/test/FreeC/PipelineTests.hs
> +  testCompletePatternPass
Try to keep this list in alphabetical order.

2020-06-18 10:46 UTC, just95 commented on src/test/FreeC/Pass/CompletePatternPassTests.hs
> +              "f x = case ((case x :: Foobar of {Foo -> x} ) :: Foobar) of {Foo -> Foo ; Bar -> Bar}"
These lines look like they exceed the 80 character limit. Use string concatenation to break up the lines. Also check other long lines in this file.

```suggestion
    it
        (  "fails for a faulty case expression used as another case"
        ++ "expression's scrutinee"
        )
      $ do
          input <-
            expectParseTestFuncDecl
            $  "f x = case ((case x :: Foobar of {Foo -> x} ) :: Foobar) of {"
            ++ "    Foo -> Foo ;"
            ++ "    Bar -> Bar"
            ++ "  }"
```

2020-06-18 10:46 UTC, just95 commented on src/test/FreeC/Pass/CompletePatternPassTests.hs
> +
```suggestion
```

2020-06-22 12:56 UTC, just95 approved these changes

2020-06-23 07:48 UTC, maclement approved these changes

2020-06-23 08:17 UTC, merged