Issue 7 tests
FreeProving/free-compiler pull request #78
Opened 2020-06-19 07:38 UTC by stu204146-kiel

Add tests for Issue 7

2020-06-20 12:32 UTC, just95 requested changes
The tests look good to me. The pipeline is currently failing because `defineTestTypeCon` has a new argument for the constructor names.

2020-06-20 12:32 UTC, just95 commented on src/test/FreeC/IR/InliningTests.hs
> +-- | This moduule contains tests for FreeC.IR.Inlining
Use Haddock markup if your comments contain code or identifiers and end sentences with a period.

```suggestion
-- | This module contains tests for "FreeC.IR.Inlining".
```

2020-06-20 12:32 UTC, just95 commented on src/test/FreeC/IR/InliningTests.hs
> +-- | Test group for inlineExpr and inlineFuncDecls
```suggestion
-- | Test group for 'inlineExpr' and 'inlineFuncDecls'.
```

2020-06-20 12:32 UTC, just95 commented on src/test/FreeC/IR/InliningTests.hs
> +          "add (m :: Peano) (n :: Peano) :: Peano = case m of { Zero -> n ; Succ m' -> Succ (add' m n) }"
This line looks like it exceeds the 80 character line length limit. Brittany does not break up long string automatically. You have to insert `++` manually.

```suggestion
      add <-
        parseTestFuncDecl
        $  "add (m :: Peano) (n :: Peano) :: Peano = case m of {"
        ++ "   Zero -> n;"
        ++ "   Succ m' -> Succ (add' m n)"
        ++ "}"
```

Also check remaining lines in this file.

2020-06-24 09:04 UTC, just95 approved these changes

2020-06-30 07:02 UTC, jo-hanna1997 approved these changes

2020-06-30 07:19 UTC, merged