Add files for Hutton's Razor
FreeProving/free-compiler pull request #89
Opened 2020-06-24 13:54 UTC by marvin2706

### Issue

Closes #82

### Description of the Change

This pull request adds:
- An haskell file containing Hutton's Razor and some properties that have to be proven.
- A coq file containing the proofs for the properties mentioned above.

### Alternate Designs

### Possible Drawbacks

### Verification Process

The proofs are directly verified using coq.

2020-06-24 14:16 UTC, ichistmeinname commented on example/Proofs/RazorProofs.v
> +Qed.
You haven't used these lemmas yet, but I think when working with `Free` it's preferable not to reuse the monadic properties. In a pen-and-paper-proof, when we usually only consider the total setting, such reasoning steps are not part of the proof. In the best case we want to the user to have as less overhead in contrast to the total setting as possible.

2020-07-02 06:26 UTC, ichistmeinname commented on example/Proofs/RazorProofs.v
> +        exec Shape Pos Partial (append Shape Pos fcode1 fcode2) fstack
Hutton himself states the following invariant for this theorem.

>  provided that we assume that exec is strict in its stack argument (exec ⊥ ops = ⊥.)

https://nottingham-repository.worktribe.com/preview/1021572/exceptions.pdf (directly following Lemma 1)

2020-07-08 06:33 UTC, ichistmeinname commented on example/CaseStudyHuttonsRazor/RazorProofsPureCodes.v
> +        = impure sStack (fun p => exec Shape Pos Partial (Cons Shape Pos (pure op) fcode) (pfStack p)).
The `impure`-calls are very specific -- can we generalise them to use `undefined` instead?

2020-07-08 06:33 UTC, ichistmeinname commented on example/CaseStudyHuttonsRazor/RazorProofsPureCodes.v
> +  Qed.
I already mentioned last time that I don't think it's a good abstraction to let the user see or use lemmas like `bind_pure` and `bind_assoc` as they are meta-lemmas.
I'd suggest that yo do not need to change your proofs now, as we want to see if the simplification-lemmas help to get rid of `>>=` showing up all the time.

2020-07-14 11:38 UTC, marvin2706 commented on example/CaseStudyHuttonsRazor/RazorProofsPureCodes.v
> +        = impure sStack (fun p => exec Shape Pos Partial (Cons Shape Pos (pure op) fcode) (pfStack p)).
If the properties `UndefinedIsImpure` and `UndefinedHasNoPositions` hold, we could specialize these lemmata to use `undefined` on both sides of the equation. But this would of course make these lemmata not applicable if we have an impure stack that doesn't represent an `undefined` value.
Therefore we would need to require that `undefined` is the only impure value, which would result in the `Maybe` monad as we see in `RazorProofsMaybe`, or we would need the stack in the `exec_append` lemma to contain no impure value other than `undefined`.

2020-07-14 11:45 UTC, marvin2706 commented on example/CaseStudyHuttonsRazor/RazorProofsPureCodes.v
> +  Qed.
I think the lemma `exec_append` is formulated too general. I didn't manage to solve the complex impure cases without those lemmata yet. The lemma `bind_pure` could at least be added to an hint database like the `prettyDB`, that was added with the latest commits, and this way be hidden behind a `pretty` call.

2020-07-14 18:40 UTC, marvin2706 commented on example/CaseStudyHuttonsRazor/RazorProofsPureCodes.v
> +  Qed.
I have finished those impure simplification-lemmas and reworked this proof in `RazorProofsPureCodesPretty`. In this new proof I didn't need those bind-lemmas and neither that `match_stack` lemma.

2020-07-14 18:44 UTC, marvin2706 commented on example/CaseStudyHuttonsRazor/RazorProofsPureCodes.v
> +        = impure sStack (fun p => exec Shape Pos Partial (Cons Shape Pos (pure op) fcode) (pfStack p)).
In the reworked proof (see conversation below) this lemma here is one example of the new impure simplification-lemmas for the hint-database. I replaced this lemma here with the specialized `undefined` version.

2020-09-30 16:41 UTC, MajaRet requested changes

2020-09-30 16:41 UTC, MajaRet commented on example/CaseStudyHuttonsRazor/Extra/Pureness.v
> +   this tactic tries to do this. *)
I think this comment sounds a little awkward.

```suggestion
(* If the goal is to prove one the above pureness properties, this tactic tries to do that. *)
```

2020-09-30 16:41 UTC, MajaRet commented on example/CaseStudyHuttonsRazor/Extra/Pureness.v
> +  (* If we apply [append] on to pieces of recursively pure code the result is recursively pure code. *)
```suggestion
  (* If we apply [append] on two pieces of recursively pure code the result is recursively pure code. *)
```

2020-09-30 16:41 UTC, MajaRet commented on example/CaseStudyHuttonsRazor/Extra/Pureness.v
> +    - (* The first operation in a non empty [code1] is pure. *)
```suggestion
    - (* The first operation in a non-empty [code1] is pure. *)
```

2020-09-30 16:41 UTC, MajaRet commented on example/CaseStudyHuttonsRazor/RazorProofs.v
> +(* This file contains some naive proofs for the properties of the haskell file. *)
```suggestion
(* This file contains some naive proofs for the properties of the Haskell file. *)
```

2020-09-30 16:41 UTC, MajaRet commented on example/CaseStudyHuttonsRazor/RazorProofs.v
> +(* This property states, that the given Partial instance represents every [undefined] as an impure value. *)
```suggestion
(* This property states that the given Partial instance represents every [undefined] as an impure value. *)
```

2020-09-30 16:41 UTC, MajaRet commented on example/CaseStudyHuttonsRazor/RazorProofs.v
> +(* This is a tactic, which discriminates assumptions where [impure] is equal to some [pure] value. *)
```suggestion
(* This is a tactic which discriminates assumptions where [impure] is equal to some [pure] value. *)
```

2020-09-30 16:41 UTC, MajaRet commented on example/CaseStudyHuttonsRazor/RazorProofs.v
> +        (* Prove subgoals, that were introduced by the [replace] tactic, by induction. *)
```suggestion
        (* Prove subgoals that were introduced by the [replace] tactic by induction. *)
```

2020-09-30 16:41 UTC, MajaRet commented on example/CaseStudyHuttonsRazor/RazorProofsMaybe.v
> +(* This file contains a naive proofs for one of the properties of the haskell file.
```suggestion
(* This file contains a naive proofs for one of the properties of the Haskell file.
```

2020-09-30 16:41 UTC, MajaRet commented on example/CaseStudyHuttonsRazor/RazorProofsMaybe.v
> +  (* In the [Maybe] monad exists only one impure value. *)
```suggestion
  (* In the [Maybe] monad there exists only one impure value. *)
```

2020-09-30 16:41 UTC, MajaRet commented on example/CaseStudyHuttonsRazor/RazorProofsMaybe.v
> +        (* Destruct the remaining code [fcode1'] to see, wether it is pure or impure. *)
```suggestion
        (* Destruct the remaining code [fcode1'] to see wether it is pure or impure. *)
```

2020-09-30 16:41 UTC, MajaRet commented on example/CaseStudyHuttonsRazor/RazorProofsMaybe.v
> +        (* Destruct the remaining code [fcode1'] to see, wether it is pure or impure. *)
```suggestion
        (* Destruct the remaining code [fcode1'] to see wether it is pure or impure. *)
```

2020-09-30 16:41 UTC, MajaRet commented on example/CaseStudyHuttonsRazor/RazorProofsMaybe.v
> +             All cases, where the stack does not contain at least two values, produce an undefined. *)
```suggestion
             All cases where the stack does not contain at least two values produce an undefined. *)
```

2020-09-30 16:41 UTC, MajaRet commented on example/CaseStudyHuttonsRazor/RazorProofsMaybe.v
> +     need the precondition, that the given expression is recursively pure. *)
```suggestion
     need the precondition that the given expression is recursively pure. *)
```

2020-09-30 16:41 UTC, MajaRet commented on example/CaseStudyHuttonsRazor/RazorProofsMaybe.v
> +     given expression is recursively pure. *)
```suggestion
  (* The theorem derived by the correctness QuickCheck property for comp_correct
     can now be proven with the more general lemma above and under the assumption that the
     given expression is recursively pure. *)
```

2020-09-30 16:41 UTC, MajaRet commented on example/CaseStudyHuttonsRazor/RazorProofsMaybePretty.v
> +        (* Check wether there are enough values in the stack for addition. *)
```suggestion
        (* Check whether there are enough values in the stack for addition. *)
```

2020-09-30 16:41 UTC, MajaRet commented on example/CaseStudyHuttonsRazor/RazorProofsMaybePretty.v
> +     given expression is recursively pure. *)
```suggestion
  (* The theorem derived by the correctness QuickCheck property for comp_correct
     can now be proven with the more general lemma above and under the assumption that the
     given expression is recursively pure. *)
```

2020-09-30 16:41 UTC, MajaRet commented on example/CaseStudyHuttonsRazor/RazorProofsPureCodes.v
> +(* This property states, that the given Partial instance represents every [undefined] as an impure value. *)
```suggestion
(* This property states that the given Partial instance represents every [undefined] as an impure value. *)
```

2020-09-30 16:41 UTC, MajaRet commented on example/CaseStudyHuttonsRazor/RazorProofsPureCodes.v
> +(* This property states, that the given Partial instance has no positions in an impure [undefined]. *)
```suggestion
(* This property states that the given Partial instance has no positions in an impure [undefined]. *)
```

2020-09-30 16:41 UTC, MajaRet commented on example/CaseStudyHuttonsRazor/RazorProofsPureCodesPretty.v
> +(* This property states, that the given Partial instance represents every [undefined] as an impure value. *)
```suggestion
(* This property states that the given Partial instance represents every [undefined] as an impure value. *)
```

2020-09-30 16:41 UTC, MajaRet commented on example/CaseStudyHuttonsRazor/RazorProofsPureCodesPretty.v
> +(* This property states, that the given Partial instance has no positions in an impure [undefined]. *)
```suggestion
(* This property states that the given Partial instance has no positions in an impure [undefined]. *)
```

2020-09-30 16:41 UTC, MajaRet commented on example/CaseStudyHuttonsRazor/RazorProofsPureCodesPretty.v
> +     matter wether we concatenate those pieces of code and run them on the
```suggestion
     matter whether we concatenate those pieces of code and run them on the
```

2020-09-30 16:41 UTC, MajaRet commented on example/CaseStudyHuttonsRazor/RazorProofsPureCodesPretty.v
> +    (* As we now that both pieces of code are recursively pure we, we can
```suggestion
    (* As we now that both pieces of code are recursively pure, we can
```

2020-09-30 16:41 UTC, MajaRet commented on example/CaseStudyHuttonsRazor/RazorProofsPureCodesPretty.v
> +      (* We can proof the goal per induction over the stack. *)
```suggestion
      (* We can prove the goal per induction over the stack. *)
```

2020-09-30 18:11 UTC, MajaRet approved these changes

2020-09-30 18:36 UTC, merged