Spell check block 9
FreeProving/free-compiler pull request #94
Opened 2020-06-26 13:57 UTC by JonasHoefer

2020-06-30 12:48 UTC, ichistmeinname approved these changes

2020-07-01 16:31 UTC, just95 requested changes

2020-07-01 16:31 UTC, just95 commented on src/lib/FreeC/Backend/Coq/Converter/FuncDecl/Rec/WithHelpers.hs
> +  -- The right hand sides of the main functions are inlined into the helper
```suggestion
  -- The right-hand sides of the main functions are inlined into the helper
```

There are probably a lot more unhyphenated occurrences of "right-hand" and "left-hand" side. Could you do a *find and replace* on all `.hs` files (also outside block 9)? : )

2020-07-01 16:34 UTC, JonasHoefer commented on src/lib/FreeC/Backend/Coq/Converter/FuncDecl/Rec/WithHelpers.hs
> +  -- The right hand sides of the main functions are inlined into the helper
Will do.

2020-07-02 14:31 UTC, just95 commented on src/lib/FreeC/Backend/Coq/Converter/FuncDecl/Rec/WithHelpers.hs
> +  -- The right hand sides of the main functions are inlined into the helper
Thanks : )

2020-07-02 14:31 UTC, just95 approved these changes

2020-07-02 14:32 UTC, merged